### ISSUE TITLE
ROS2サンプルデバイスを終了するとSIGSEGVで落ちる

### ISSUE THREAD

**Issue by tmori** [toppers/athrill-device#10]
以下でROS2サンプルデバイス対応したが、athrillを終了させると、SIGESGVで落ちる現象が発生している。
gdbでトレースを見た感じだと、DDS内のどこかで不正メモリアクセスが発生した模様。
もしかすると、athrill exit する前に、ros2 ノードの終了処理をやった方が良いのかもしれない。

https://github.com/toppers/athrill-device/pull/9

**Comment by tmori** [comment]
SIGTERM で athrillプロセスを終了させる場合は、SIGSEGVは発生しなかった。
おそらく、ros2のプロセスとしてシグナルハンドリングが再定義されているような気がする。

**Comment by tmori** [comment]
ros2のノードをスレッド管理(spinする)した状態で、athrillがexitする場合はSIGSEGVにならないことがわかった。

**Comment by takasehideki** [comment]
関係ないかもしれないですが，いちおう情報提供ということで．
`rclcpp::spin(node)` の振る舞いは，callbackやsignal発行などのイベントが発生するまで待つ処理になります．典型的にはSIGINT (Ctrl+C) で抜け出します．他にもLinuxのsignal発行で駆動される処理があるかもしれません．本当はユーザ側でシグナルハンドラとか真面目に実装すべきなのですが，ROSのminimalなsampleはそのあたりは雑にしています．
まぁ要するに，athrillの終了処理でなにかシグナル発行されたら，ROS 2ノードの振る舞いに影響を及ぼす可能性があります．

このあたりが参考になるかなぁと思います．
https://roboticsbackend.com/write-minimal-ros2-cpp-node/
https://graziegrazie.hatenablog.com/entry/2018/12/01/015655
http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown
